mod egl;
mod renderer;

pub use egl::{init_egl_display, EglContext};
pub use renderer::{Renderer, Texture};

// OpenGL bindings generated by build.rs
#[allow(clippy::all)]
#[allow(dead_code)]
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
pub mod gl {
    include!(concat!(env!("OUT_DIR"), "/gl_bindings.rs"));
}
